services:
  schemaspy:
    image: schemaspy/schemaspy:latest
    volumes:
      - ./schemaspy:/output
    command: -t pgsql -host db -port 5432 -u guy -p secret -db users_db
    networks:
      - projectsourcecode_default

networks:
  projectsourcecode_default:
    external: true
